import { SAMPLE_AUDIO_SECONDS } from "@/lib/data/sample-data";
import { createPlaceholderPdf, createSilentWav } from "@/lib/storage/mock-files";
import { contentDisposition } from "@/lib/storage/types";

/**
 * 개발용 mock 스토리지. 실제 파일 대신 placeholder PDF / 무음 오디오를 생성한다.
 * STORAGE_DRIVER=mock 일 때만 동작한다.
 */
export async function GET(request: Request, ctx: RouteContext<"/api/mock-storage/[...key]">) {
  if ((process.env.STORAGE_DRIVER ?? "mock") !== "mock") {
    return new Response("Not found", { status: 404 });
  }
  const { key: segments } = await ctx.params;
  const key = segments.join("/");
  if (!/^[\w\-./]+$/.test(key) || key.includes("..")) {
    return new Response("Invalid key", { status: 400 });
  }
  const url = new URL(request.url);
  const disposition =
    url.searchParams.get("disposition") === "attachment" ? "attachment" : "inline";
  let name = (url.searchParams.get("name") ?? key.split("/").pop() ?? "file").slice(0, 200);

  let body: Uint8Array<ArrayBuffer>;
  let contentType: string;
  if (key.endsWith(".pdf")) {
    body = createPlaceholderPdf([
      "Mogo Storage - SAMPLE PLACEHOLDER",
      "This is not a real exam file.",
      "Development mock file generated by /api/mock-storage.",
      `storage key: ${key}`,
    ]);
    contentType = "application/pdf";
  } else if (key.endsWith(".mp3")) {
    // mock 에서는 mp3 인코더 없이 무음 WAV 를 돌려준다.
    body = createSilentWav(SAMPLE_AUDIO_SECONDS);
    contentType = "audio/wav";
    name = name.replace(/\.mp3$/i, ".wav");
  } else {
    return new Response("Not found", { status: 404 });
  }

  const headers = new Headers({
    "content-type": contentType,
    "content-disposition": contentDisposition(disposition, name),
    "accept-ranges": "bytes",
    "cache-control": "public, max-age=3600",
    "x-robots-tag": "noindex",
  });

  // 오디오 탐색(seek)을 위해 Range 요청 지원
  const range = request.headers.get("range");
  const match = range ? /^bytes=(\d*)-(\d*)$/.exec(range) : null;
  if (match && (match[1] || match[2])) {
    const size = body.byteLength;
    let start = match[1] ? Number(match[1]) : size - Number(match[2]);
    let end = match[1] && match[2] ? Number(match[2]) : size - 1;
    start = Math.max(0, start);
    end = Math.min(size - 1, end);
    if (start > end || start >= size) {
      headers.set("content-range", `bytes */${size}`);
      return new Response(null, { status: 416, headers });
    }
    headers.set("content-range", `bytes ${start}-${end}/${size}`);
    headers.set("content-length", String(end - start + 1));
    return new Response(body.slice(start, end + 1), { status: 206, headers });
  }

  headers.set("content-length", String(body.byteLength));
  return new Response(body, { status: 200, headers });
}
